FROM node:latest as build-stage
WORKDIR /depo23_vue
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /depo23_vue/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
